name: PySchemia-Crypto CI

on:
  push:
    branches: [ main, legacy, experimental, 'release/*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        crypto-layer: ["legacy", "stable", "experimental"]
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Run linting
      run: |
        flake8 pyschemia_crypto/ --count --select=E9,F63,F7,F82 --show-source --statistics
        mypy pyschemia_crypto/ --ignore-missing-imports
    
    - name: Validate pattern compliance
      run: |
        python -m pytest tests/test_patterns.py -v
    
    - name: Test normalization compliance
      run: |
        python -m pytest tests/test_normalization.py -v
    
    - name: Generate coverage report
      run: |
        pytest --cov=pyschemia_crypto --cov-report=xml --cov-report=html
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
